### ISSUE TITLE
Error with accented characters or special characters in CircleText

### ISSUE THREAD

**Issue by Ichunjo** [TypesettingTools/lyger-Aegisub-Scripts#9]
Line:
`Dialogue: 0,0:11:51.60,0:11:54.10,Default,,0,0,0,,{\pos(664,614)\org(656,1070)}Aaaa bbébb ccc.`
```
Lua reported a runtime error:
    File "C:/Users\Varde\AppData\Roaming\Aegisub\automation\autoload\lyger.CircleText.lua", line 159
<anonymous function at lines 67-232>
    File "<C function>", line -1
?
One or more characters in the input string were not valid characters in the given input encoding```

**Comment by ghost** [comment]
This error occurs because this script does not support special characters, that is, if you are using a character with an accent in a certain way it is a special character. To resolve this, remove the accent or special character, apply it without an accent and then change it manually.
